### ISSUE TITLE
Example code from the documentation seems to give wrong results

### ISSUE THREAD

**Issue by hronellenfitsch** [JuliaDiffEq/DiffEqSensitivity.jl#111]
I was trying to go through the documentation for adjoint sensitivity analysis.
In addition to having to fix some function signatures that were incorrect in the documentation, the resulting sensitivities seem to be wrong when compared to autodifferentiation and finite differences.

I am following the documentation with this code:

`using DifferentialEquations
using DiffEqSensitivity

function f(du,u,p,t)
  du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = dy = -p[3]*u[2] + u[1]*u[2]
end

p = [1.5,1.0,3.0]
prob = ODEProblem(f,[1.0; 1.0],(0.0, 10.0),p)
sol = solve(prob,Vern9(),abstol=1e-10,reltol=1e-10);

dg(out,u,p,t,i) = (out .= 1.0 .- u) # this function signature is wrong/incomplete in the documentation

t = [0.5, 1.0] # this definition is missing from the documentation

res = adjoint_sensitivities(sol,Vern9(),dg,t,abstol=1e-14,
                            reltol=1e-14,iabstol=1e-14,ireltol=1e-12)`

which results in
`1×3 LinearAlgebra.Adjoint{Float64,Array{Float64,1}}:
 0.616953  -0.357961  0.100422`

Again, copying the code from the documentation to check against other methods:

`
using ForwardDiff, Calculus
function G(p)
  tmp_prob = remake(prob,u0=convert.(eltype(p),prob.u0),p=p)
  sol = solve(tmp_prob,Vern9(), abstol=1e-14, reltol=1e-14, saveat=t)
  A = convert(Array,sol)
    
  sum(((1 .- A).^2)./2)
end

@show G([1.5,1.0,3.0])
@show res2 = ForwardDiff.gradient(G,[1.5,1.0,3.0])
@show res3 = Calculus.gradient(G,[1.5,1.0,3.0]);
`

which results in the entirely different (but consistent) gradients

`
G([1.5, 1.0, 3.0]) = 2.161316471053881
res2 = ForwardDiff.gradient(G, [1.5, 1.0, 3.0]) = [4.698722374012723, -2.227674237734399, 1.1820220043862988]
res3 = Calculus.gradient(G, [1.5, 1.0, 3.0]) = [4.698722373289014, -2.227674241910004, 1.1820220061302733]
`

**Comment by ChrisRackauckas** [comment]
Interesting. I'd compare it to the tests: https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/blob/master/test/adjoint.jl

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/112

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
