### ISSUE TITLE
Regression needs tests and optimizations

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqSensitivity.jl#18]
@Vaibhavdixit02

**Comment by Vaibhavdixit02** [comment]
https://github.com/JuliaStats/StatsBase.jl/blob/cc9ad6ea170897ca2f817ca6b58fe26445bf29da/src/cov.jl#L106 try this instead of manual correlation calculation.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/187
