### ISSUE TITLE
Unify regression_sensitivity with other GSAs

### ISSUE THREAD

**Issue by platawiec** [JuliaDiffEq/DiffEqSensitivity.jl#185]
`regression_sensitivity` could use some updating to be unified with the rest of the GSA methods. From a cursory look, it needs a `batch` kwarg. It also generates sampling points via a naked call to `rand()`, this could be improved by passing in a sampler using `QuasiMonteCarlo` to generate the samples instead. This would address #15 as well.

We could also consider unifying it with the rest of the GSA methods by providing a `gsa` call. The trouble here is that it requires a fixed point to calculate the regression around - perhaps a default could be the mean value of the `p_ranges` passed, or the dispatch struct `Regression` could require a `p0` to be passed. The user could then call:
```
gsa(f, Regression(p0), p_range, samples, batch)
```

**Comment by ChrisRackauckas** [comment]
Yes indeed it needs an update. Thanks for the issue!

**Comment by platawiec** [comment]
I had a deeper look and noted the following concerns. Would appreciate any thoughts on the best way to resolve

- `regression_sensitivity` seems to want the output of `f` to be an array. Unfortunately, this is both undocumented and I couldn't find any tests for it! It then does a weird thing when computing the standard regression coefficient in `pcs_and_srcs`, where it [omits](https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/blob/908e3078bfbbc10cbf6d150db19c6ff5f8e8c728/src/global_sensitivity/regression_sensitivity.jl#L118) the first value along one dimension of the resulting `VectorOfArray`. It _seems_ to build a three-dimensional array, where the last dimension is the samples taken along the axis. The other two axes could support a multi-dimensional output, but because these are ostensibly derived from the user-provided function, and it's not clear what its doing. This might just be code rot and need to be re-written.
- When sampling points for the regression, it freezes all dimensions but one, and samples along that axis. This process is repeated for each dimension. I'm fairly certain that for this analysis, the correct thing to do is instead sample within the entire region and then estimate the linear coefficients for each dimension (and so on for the other statistics). In other words, it shouldn't be freezing any of the dimensions. We also don't need to specify any fixed point.

**Comment by ChrisRackauckas** [comment]
>regression_sensitivity seems to want the output of f to be an array. Unfortunately, this is both undocumented and I couldn't find any tests for it! It then does a weird thing when computing the standard regression coefficient in pcs_and_srcs, where it omits the first value along one dimension of the resulting VectorOfArray. It seems to build a three-dimensional array, where the last dimension is the samples taken along the axis. The other two axes could support a multi-dimensional output, but because these are ostensibly derived from the user-provided function, and it's not clear what its doing. This might just be code rot and need to be re-written.

We should change it to match the other GSA methods.

>When sampling points for the regression, it freezes all dimensions but one, and samples along that axis. This process is repeated for each dimension. I'm fairly certain that for this analysis, the correct thing to do is instead sample within the entire region and then estimate the linear coefficients for each dimension (and so on for the other statistics). In other words, it shouldn't be freezing any of the dimensions. We also don't need to specify any fixed point.

Indeed, it sounds like what it's currently doing is incorrect. It should just do a regression on a QMC sample.

**Comment by platawiec** [comment]
I can take a look over the weekend. The fix should also address #99 and #166

**Comment by ChrisRackauckas** [comment]
Awesome thanks!
