### ISSUE TITLE
Sensitivites with respect to initial values

### ISSUE THREAD

**Issue by felixlen** [JuliaDiffEq/DiffEqSensitivity.jl#6]
I am not sure if I missed this, but if so I couldn't find anything in the docs: Is it possible to compute derivatives of the solution with respect to initial values? This is crucial for shooting methods.

**Comment by ChrisRackauckas** [comment]
We don't have a way to have the initial condition dependent on the parameters. 

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/251

I plan to do this today though since it will solve this problem, among others. Sensitivity analysis will need to be updated to know about this though.

**Comment by felixlen** [comment]
Thanks, looking forward to it. As you pointed out, this needs a change in the sensitivity module. If you allow for an initial condition u0 = g(p), then the initial value for sensitivites has to be dg/dp instead of 0.

**Comment by axsk** [comment]
Since I needed the sensivities wrt. to the initial values as well I put together this [gist](https://gist.github.com/axsk/5d1e3d49a53ce331e5ef6e7daec23b8d), which uses Sundials.jl/CVODES for the solution.

cf. [the cvodes issue](https://github.com/JuliaDiffEq/Sundials.jl/issues/38).

**Comment by ChrisRackauckas** [comment]
Thanks for the gist! I got a bit behind on this. The CVODES setup will be good for testing/benchmarking!

**Comment by ChrisRackauckas** [comment]
adjoint_sensitivities_u0 handles this.
