### ISSUE TITLE
More flexible parameters

### ISSUE THREAD

**Issue by MikeInnes** [JuliaDiffEq/DiffEqSensitivity.jl#66]
I'd like to prototype DiffEqFlux with Zygote, which will have a much nicer API and generally improve all the things. However, to do that we need to make DiffEqSensitivity a but more flexible in terms of what kinds of parameters we can integrate over.

Currently, we only support a fixed-length vector. The key generalisation we need is to make this vector growable (which should be mathematically sensible, just act as if new elements were `0` in all previous time steps). As long as we have this it's easy to linearise any complex nested data structure, even when the structure changes over time.

Growable vectors are the simplest way to support Zygote but may not be the best; e.g. perhaps DiffEq should support nested key-value pairs with key paths as indices directly. In any case, I'm happy to help out with the higher-level parts but will need some expertise on the DiffEq side for the lower-level changes.

**Comment by ChrisRackauckas** [comment]
Since DiffEqSenstivity is just using the DiffEq solvers themselves, this is actually a question of what array types DiffEq supports. It just needs the ability to do linear combinations via broadcast, and broadcast to a vector to do linear algebra in some (consistent Jacobian definition). Resizing in DiffEq works by having `resize(integrator)` working, but of course that's only required if you're resizing during the ODE solve. I assume that won't be happening in the backpass?

**Comment by MikeInnes** [comment]
Right. One option might be to just define the Jacobian of a namedtuple input in some reasonable way and use that everywhere; Zygote could support that and it might avoid other issues, like needing to resize.

The resizing case comes up when you have a function like

```
p = (W, V)
f(x) = p[rand(1:2)] * x
```

for which the gradient `dp` is alternately `(nothing, dV)` and `(dW, nothing)`. The way to handle this, I think, is to initially assume the parameter vector is just `vec(dV)`, and then later grow it to include `vec(dW)`. You'd have to be careful about the mapping from structured-parameter to linearised one, but that's all on my end.

**Comment by ChrisRackauckas** [comment]
That term cannot show up in an ODE though otherwise it doesn't have a unique solution, so we're fine.

**Comment by MikeInnes** [comment]
The `rand` call here is not really the point. In general this can happen in any number of ways (e.g. you could write lotka-volterra in a way that raises this issue).

**Comment by ChrisRackauckas** [comment]
Can you show that example?

**Comment by MikeInnes** [comment]
```julia
f(x) = p[sum(x) > 10 ? 1 : 2] * x
```

You can pick holes about this being realistic or not if you want, but there's going to be somewhere that this can come up: it's a property of how our AD works.

**Comment by ChrisRackauckas** [comment]
No, you're missing the point there. That kind of branching isn't supposed to be done in an ODE anyways since it's a discontinuity which needs a ContinuousCallback for handling without order reduction, and adjoints aren't compatible with a ContinuousCallback without a much larger adjoint equation.

**Comment by ChrisRackauckas** [comment]
And actually, the adjoint vector isn't sized off of the parameters anyways, it's sized off of the initial condition, so that shouldn't be an issue. The only place the parameters show up are in the vjps against the parameter Jacobian. If lambda' * df/dp  can be done with p being anything Zygote likes, and Zygote does the vjp, then it all works out.

**Comment by MikeInnes** [comment]
It's possible to implement continuous functions using branches for the implementation (most are). The guarantee you're making here is that no ODE function ever has any kind of conditional dependence on its parameters; I doubt this is really the case, even if it's pretty unusual.

The `u` for the adjoint solve is effectively `vcat(du, dp)` right now, so I don't understand your comment. Even without the resizing issue,  the view of parameter adjoints as vectors is [very much hard-coded in](https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/blob/4a235e9cba1e3a110f538d804fcd48821a389f0b/src/adjoint_sensitivity.jl#L346).

**Comment by ChrisRackauckas** [comment]
>It's possible to implement continuous functions using branches for the implementation (most are). The guarantee you're making here is that no ODE function ever has any kind of conditional dependence on its parameters; I doubt this is really the case, even if it's pretty unusual.

No, it's that if you want it to be accurate you need to use event handling, and if you use event handling then the adjoints are wrong, so this is a much deeper issue with ODEs than just doing branching. You can someone rely on adaptivity maybe, but that's really slow and technically you loose all order of accuracy. At that point you likely need to just AD the solver though.

>The u for the adjoint solve is effectively vcat(du, dp) right now, so I don't understand your comment. Even without the resizing issue, the view of parameter adjoints as vectors is very much hard-coded in.

Oh yes, when not using the quadrature.

**Comment by MikeInnes** [comment]
>  if you want it to be accurate you need to use event handling, and if you use event handling then the adjoints are wrong

I don't see how this can be true in all possible cases. If I write

```julia
function lotka_volterra(u,p,t)
  x, y = u
  α, β, δ, γ = p
  dx = (α - β*γ) == 0 ? 0 : (α - β*γ)x
  dy = (δ*x - γ) == 0 ? 0 : (δ*x - γ)y
  [dx, dy]
end
```

Then this is mathematically identical to the original lotka-volterra – so presumably doesn't suddenly break the adjoint method – but does have the `nothing` gradient issue.

**Comment by ChrisRackauckas** [comment]
If you want perfect zero handling you'd need to use event handling whether or not you write the if statement here. The reason why this doesn't show up in Lotka-Volterra is because it won't hit zero until infinity. Computationally, you can have an issue if you bring time out long enough.

But yes, this is just the unrelated issue that AD can fail on programs even if they are "mathematically correct" in some sense. AD of a lookup table is one example.

But why would branching change the size of the parameters in AD?

**Comment by MikeInnes** [comment]
AD _doesn't_ fail in this case – it just returns `nothing` rather than a zero of the appropriate type. And `dx` clearly crosses through `0` here when the solution oscillates, so it's possible to get `dα == nothing` here rather than `dα == 0` during the adjoint solve. This is just nonsense.

Anyway, whatever, we can just do without and wait for a user to hit this.

**Comment by ChrisRackauckas** [comment]
Yeah, it's a user issue. More info: https://discourse.julialang.org/t/handling-instability-when-solving-ode-problems/9019/5 . We can just tell them to fix the problem the same way you'd fix this problem in ODEs in any other case.

**Comment by MikeInnes** [comment]
At the risk of beating a dead horse here, one case where this comes up *without* breaking the adjoint method is `relu` and `leakyrelu`, i.e. `leakyrelu(x, r) = x < 0 ? r * x : x`. I can imagine there are all sorts of caveats around integrating branches, but still the fact remains that I can be working productively with something like this *right now*, and tweaking it to store parameters in a struct will break my code.

Aside from that, if `relu` is unsafe in the adjoint method then we should probably at least document that somewhere, since it's going to be an obvious choice for many people working with neural ODEs otherwise.
