### ISSUE TITLE
Morris Mean/Variance calculation over wrong dimension?

### ISSUE THREAD

**Issue by cg1234** [JuliaDiffEq/DiffEqSensitivity.jl#78]
It seems to me that the means and variances are calculated over the whole simulation time and not over the elementary effects for each time point.

If I run the example code from the documentation (http://docs.juliadiffeq.org/latest/analysis/global_sensitivity.html):
```
function f(du,u,p,t)
  du[1] = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = -3*u[2] + u[1]*u[2]
end
u0 = [1.0;1.0]
tspan = (0.0,10.0)
p = [1.5,1.0]
prob = ODEProblem(f,u0,tspan,p)
t = collect(range(0, stop=10, length=200))
m = DiffEqSensitivity.morris_sensitivity(prob,Tsit5(),t,[[1,5],[0.5,5]],[10,10],len_trajectory=1500,total_num_trajectory=1000,num_trajectory=150)
```
I would expect an output array of length 200 for each parameter and output combination (as written in the documentation). But on my installation I will get very lengthy arrays instead.

Elementary effects are correct:
```
size.(m.elementary_effects[1])
```

gives

```
107759-element Array{Tuple{Int64,Int64},1}:
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 ⋮       
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
 (2, 200)
```

but
`size.(m.means)`

gives
```
2-element Array{Tuple{Int64,Int64,Int64},1}:
 (2, 1, 107759)
 (2, 1, 117091)
```
107759+ 117091 = 224850 is exactly the number of samples (len_trajectory*num_trajectory-150 = 1500×150−150 = 224850)!

If I calculate the means and variances by hand (just changing dims from 2 to 3) I will get following:

```
means = []
variances = []
for k in m.elementary_effects
    push!(means,mean(convert(Array, VectorOfArray(k)),dims=3))
    push!(variances,var(convert(Array, VectorOfArray(k)),dims=3))
end
means[1]
```

which gives
```
2×200×1 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0513992  0.106989    0.169601    …  7.24055  7.67254  7.95    7.98303
 0.0  0.0011582  0.00429882  0.00909004     3.84639  3.7428   3.6888  3.68657
```

which seems to be correct.

Please, could someone check this! Maybe this could also be a problem on my local installation.

Thanks a lot!

**Comment by Vaibhavdixit02** [comment]
This seems to be working correctly on the `master` branch. Can you try to use that? (Or we could have a new release soonish @ChrisRackauckas?)

**Comment by cg1234** [comment]
Thanks for the very quick reply!

Your are right the current master solved the problem! 👍

Thanks a lot!
