### ISSUE TITLE
Variance-based Global Sensitivity Analysis methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqSensitivity.jl#9]
http://discovery.ucl.ac.uk/19896/1/19896.pdf

- [ ] FAST
- [x] eFAST
- [x] Sobol method
- [ ] Saltelli’s scheme

**Comment by ChrisRackauckas** [comment]
Here's a whole lot of methods: https://cran.r-project.org/web/packages/sensitivity/sensitivity.pdf

**Comment by ChrisRackauckas** [comment]
Sobol still has a few changes to do, see the comments from https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/14

**Comment by ChrisRackauckas** [comment]
@Vaibhavdixit02 where are we at on this? Saltelli's scheme is just the improved error estimators I think? And is FAST necessary given eFAST?

**Comment by Vaibhavdixit02** [comment]
>Saltelli's scheme is just the improved error estimators I think? 

Yeah

>And is FAST necessary given eFAST?

Nope

**Comment by ChrisRackauckas** [comment]
Alright
